name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1

    steps:
    #  Checkout repo
    - name: Checkout repository
      uses: actions/checkout@v3

    #  Configure AWS
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    #  Terraform init & apply
    - name: Terraform Init & Apply
      run: |
        cd terraform
        terraform init
        terraform apply -auto-approve

    #  Generate dynamic Ansible inventory
    - name: Generate Ansible inventory from Terraform output
      run: |
        cd terraform
        terraform output -json instance_ips > ../ansible/inventory.json
        cd ../ansible
        jq -r '.[] | "k8s ansible_host=\(.) ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/devops-key"' inventory.json > inventory.ini

    #  Install Ansible
    - name: Install Ansible
      run: sudo apt update && sudo apt install -y ansible jq

    #  Set up SSH key
    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DEVOPS_KEY }}" > ~/.ssh/devops-key
        chmod 600 ~/.ssh/devops-key
        echo "StrictHostKeyChecking no" >> ~/.ssh/config

    #  Run Ansible playbook
    - name: Run Ansible Playbook
      run: |
        cd ansible
        ansible-playbook -i inventory.ini playbook.yaml --private-key ~/.ssh/devops-key

    #  Docker setup
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t boyyeena/myapp:latest ./app
        docker push boyyeena/myapp:latest

    #  Kubectl setup
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.28.0'

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f kubernetes/
